[package]
name = "chipioindustries/service-provider"
description = "A library for enabling injection of mock services for unit testing."
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"